spring:
  profiles:
    active: dev
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: false

qiniu:
  oss:
    accessKey: accessKey
    secretKey: secretKey
    bucket: bucket