# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/berryvideo-dev
    username: root
    password:

  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 1200
  cache:
    redis:
      time-to-live: 1800s
    cache-names: menus_cache
    type: redis

easy-es:
  address: 127.0.0.1:9200 # es连接地址+端口 格式必须为ip:port,如果是集群则可用逗号隔开
  username: elastic #如果无账号密码则可不配置此行
  password: changeme #如果无账号密码则可不配置此行