server:
  port: 10010
logging:
  level:
    cn.akfang.berry: debug
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://berry-user-consumer
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), //$\{segment}

        - id: video-service
          uri: lb://berry-video-consumer
          predicates:
            - Path=/video/**
          filters:
            - RewritePath=/video/(?<segment>.*), //$\{segment}